### ISSUE TITLE
Auto-fill navn for n-te vaffel

### ISSUE THREAD

**Issue by trondhauklien** [iverks/Vaffeltirsdag#2]
Hadde vært nice om folk som allerede er skrevet opp kommer opp som auto-fill når man skal skrive dem på n-te-listen.

**Comment by iverks** [comment]
😨🤯

**Comment by iverks** [comment]
Har ikke tid til å implementere d sjøl ass, lag pr

**Comment by iverks** [comment]
Pr ble laget, hylles
